/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as FestivalFavouritesRouteImport } from './routes/festival-favourites'
import { Route as FlipRouteImport } from './routes/flip'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as PlayRouteImport } from './routes/play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalFavouritesRoute = FestivalFavouritesRouteImport.update({
  id: '/festival-favourites',
  path: '/festival-favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const FlipRoute = FlipRouteImport.update({
  id: '/flip',
  path: '/flip',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/festival-favourites': typeof FestivalFavouritesRoute
  '/flip': typeof FlipRoute
  '/marketplace': typeof MarketplaceRoute
  '/play': typeof PlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/festival-favourites': typeof FestivalFavouritesRoute
  '/flip': typeof FlipRoute
  '/marketplace': typeof MarketplaceRoute
  '/play': typeof PlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/festival-favourites': typeof FestivalFavouritesRoute
  '/flip': typeof FlipRoute
  '/marketplace': typeof MarketplaceRoute
  '/play': typeof PlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favourites'
    | '/festival-favourites'
    | '/flip'
    | '/marketplace'
    | '/play'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favourites'
    | '/festival-favourites'
    | '/flip'
    | '/marketplace'
    | '/play'
  id:
    | '__root__'
    | '/'
    | '/favourites'
    | '/festival-favourites'
    | '/flip'
    | '/marketplace'
    | '/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavouritesRoute: typeof FavouritesRoute
  FestivalFavouritesRoute: typeof FestivalFavouritesRoute
  FlipRoute: typeof FlipRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PlayRoute: typeof PlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festival-favourites': {
      id: '/festival-favourites'
      path: '/festival-favourites'
      fullPath: '/festival-favourites'
      preLoaderRoute: typeof FestivalFavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flip': {
      id: '/flip'
      path: '/flip'
      fullPath: '/flip'
      preLoaderRoute: typeof FlipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavouritesRoute: FavouritesRoute,
  FestivalFavouritesRoute: FestivalFavouritesRoute,
  FlipRoute: FlipRoute,
  MarketplaceRoute: MarketplaceRoute,
  PlayRoute: PlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
